// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tekno_egitim_web.data;

namespace tekno_egitim_web.data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("tekno_egitim_web.core.Model.Blog", b =>
                {
                    b.Property<int>("blog_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Kategorilerkategori_id")
                        .HasColumnType("int");

                    b.Property<string>("aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<bool>("blog_silme")
                        .HasColumnType("bit");

                    b.Property<string>("imageUrl")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("kategori_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("olusturulma")
                        .HasColumnType("datetime");

                    b.HasKey("blog_id");

                    b.HasIndex("Kategorilerkategori_id");

                    b.ToTable("Blog");
                });

            modelBuilder.Entity("tekno_egitim_web.core.Model.Haber", b =>
                {
                    b.Property<int>("haber_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Kategorilerkategori_id")
                        .HasColumnType("int");

                    b.Property<string>("aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<bool>("haber_silme")
                        .HasColumnType("bit");

                    b.Property<string>("imageUrl")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("kategori_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("olusturulma")
                        .HasColumnType("datetime");

                    b.HasKey("haber_id");

                    b.HasIndex("Kategorilerkategori_id");

                    b.ToTable("Haber");
                });

            modelBuilder.Entity("tekno_egitim_web.core.Model.Kategoriler", b =>
                {
                    b.Property<int>("kategori_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Silme")
                        .HasColumnType("bit");

                    b.Property<string>("kategori_ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("kategori_id");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("tekno_egitim_web.core.Model.Makale", b =>
                {
                    b.Property<int>("makale_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Kategorilerkategori_id")
                        .HasColumnType("int");

                    b.Property<string>("aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("imageUrl")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("kategori_id")
                        .HasColumnType("int");

                    b.Property<bool>("makale_silme")
                        .HasColumnType("bit");

                    b.Property<DateTime>("olusturulma")
                        .HasColumnType("datetime");

                    b.HasKey("makale_id");

                    b.HasIndex("Kategorilerkategori_id");

                    b.ToTable("Makale");
                });

            modelBuilder.Entity("tekno_egitim_web.core.Model.Not", b =>
                {
                    b.Property<int>("not_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Kategorilerkategori_id")
                        .HasColumnType("int");

                    b.Property<string>("aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("imageUrl")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("kategori_id")
                        .HasColumnType("int");

                    b.Property<bool>("not_silme")
                        .HasColumnType("bit");

                    b.Property<DateTime>("olusturulma")
                        .HasColumnType("datetime");

                    b.HasKey("not_id");

                    b.HasIndex("Kategorilerkategori_id");

                    b.ToTable("Not");
                });

            modelBuilder.Entity("tekno_egitim_web.core.Model.Video", b =>
                {
                    b.Property<int>("video_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Kategorilerkategori_id")
                        .HasColumnType("int");

                    b.Property<string>("aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("kategori_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("olusturulma")
                        .HasColumnType("datetime");

                    b.Property<string>("videoUrl")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<bool>("video_silme")
                        .HasColumnType("bit");

                    b.HasKey("video_id");

                    b.HasIndex("Kategorilerkategori_id");

                    b.ToTable("Video");
                });

            modelBuilder.Entity("tekno_egitim_web.core.Models.Sahıs", b =>
                {
                    b.Property<int>("sahis_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("sahis_ad")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("sahis_soyad")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("sahis_id");

                    b.ToTable("Sahis");
                });

            modelBuilder.Entity("tekno_egitim_web.core.Model.Blog", b =>
                {
                    b.HasOne("tekno_egitim_web.core.Model.Kategoriler", "Kategoriler")
                        .WithMany("Blogs")
                        .HasForeignKey("Kategorilerkategori_id");
                });

            modelBuilder.Entity("tekno_egitim_web.core.Model.Haber", b =>
                {
                    b.HasOne("tekno_egitim_web.core.Model.Kategoriler", "Kategoriler")
                        .WithMany("Habers")
                        .HasForeignKey("Kategorilerkategori_id");
                });

            modelBuilder.Entity("tekno_egitim_web.core.Model.Makale", b =>
                {
                    b.HasOne("tekno_egitim_web.core.Model.Kategoriler", "Kategoriler")
                        .WithMany("Makales")
                        .HasForeignKey("Kategorilerkategori_id");
                });

            modelBuilder.Entity("tekno_egitim_web.core.Model.Not", b =>
                {
                    b.HasOne("tekno_egitim_web.core.Model.Kategoriler", "Kategoriler")
                        .WithMany("Nots")
                        .HasForeignKey("Kategorilerkategori_id");
                });

            modelBuilder.Entity("tekno_egitim_web.core.Model.Video", b =>
                {
                    b.HasOne("tekno_egitim_web.core.Model.Kategoriler", "Kategoriler")
                        .WithMany("Videos")
                        .HasForeignKey("Kategorilerkategori_id");
                });
#pragma warning restore 612, 618
        }
    }
}
